### ISSUE TITLE
readme页面内有很宽的表格时，左右滑动和tab滑动冲突

### ISSUE THREAD

**Issue by kezhenxu94** [ThirtyDegreesRay/OpenHub#112]
示例

https://github.com/toddmotto/public-apis

**Comment by crupest** [comment]
It may be because ` ViewPager `  and ` WebView `  scroll events conflict.  
I find a similar problem on [stackoverflow](https://stackoverflow.com/questions/25522731/scroll-event-conflict-in-android-webview-when-webviews-parent-is-a-viewpager) . But it seems there is no good solution under the problem by now.
